server {
    listen 80;
    server_name devops.shawnlin.online;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Cache static assets
    location ~* \.(html|css|js|png|jpg|svg)$ {
        expires 1h;
        add_header Cache-Control "public, immutable";
    }
}
